# Generated by Django 3.2.4 on 2021-10-12 07:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_title', models.CharField(max_length=100)),
                ('service_short_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('service_point1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('service_point2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('service_point3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('service_point4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('service_fee', models.PositiveSmallIntegerField(default=0, verbose_name='Service fee')),
                ('slug', models.SlugField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ('-service_title',),
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripeid',
        ),
        migrations.AlterField(
            model_name='book_list',
            name='subscription_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
