# Generated by Django 3.2.4 on 2021-10-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0002_auto_20211012_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_img',
            field=models.ImageField(blank=True, upload_to='book_img', verbose_name='book Image'),
        ),
    ]
