# Generated by Django 3.2.8 on 2021-10-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0005_servicesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
