# Generated by Django 3.2.8 on 2021-10-13 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0006_chapter_chapter_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bapp.chapter')),
            ],
        ),
    ]
