# Generated by Django 3.2.8 on 2021-10-14 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0007_chapterfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterfiles',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_files', to='bapp.chapter'),
        ),
    ]
