# Generated by Django 3.2.8 on 2021-10-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0008_alter_chapterfiles_chapter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChapterFiles',
        ),
    ]
