# Generated by Django 3.2.8 on 2021-10-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0010_chapter_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='position',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
